import type { Product } from "../../types";

export default [
  {
    section: "men",
    category: "outwear",
    subcategory: "hoodies",
    id: "4",
    name: "Pullover Hoodie",
    description: "Soft pullover hoodie with front pocket.",
    sizes: [{ size: "S" }, { size: "M" }, { size: "L" }],
    photos: [],
    price: 45,
  },
  {
    section: "men",
    category: "outwear",
    subcategory: "hoodies",
    id: "5",
    name: "Zip-Up Hoodie",
    description: "Black zip-up hoodie with drawstring.",
    sizes: [{ size: "M" }, { size: "L" }],
    photos: [],
    price: 55,
  },
  {
    section: "men",
    category: "outwear",
    subcategory: "hoodies",
    id: "6",
    name: "Oversized Hoodie",
    description: "Warm oversized hoodie in gray.",
    sizes: [{ size: "M" }, { size: "L" }, { size: "XL" }],
    photos: [],
    price: 65,
  },
  {
    section: "men",
    category: "outwear",
    subcategory: "hoodies",
    id: "7",
    name: "Graphic Print Hoodie",
    description: "Hoodie with a bold front print.",
    sizes: [{ size: "S" }, { size: "M" }, { size: "L" }],
    photos: [],
    price: 50,
  },
  {
    section: "men",
    category: "outwear",
    subcategory: "hoodies",
    id: "8",
    name: "Fleece Hoodie",
    description: "Cozy fleece hoodie for colder days.",
    sizes: [{ size: "M" }, { size: "L" }],
    photos: [],
    price: 70,
  },
  {
    section: "men",
    category: "outwear",
    subcategory: "hoodies",
    id: "9",
    name: "Sport Hoodie",
    description: "Lightweight hoodie ideal for workouts.",
    sizes: [{ size: "S" }, { size: "M" }, { size: "L" }, { size: "XL" }],
    photos: [],
    price: 40,
  },
] as Product[];