import type { Product } from "../../types";
import leatherJac1 from './images/jackets/leatherJac1.jpg'
import leatherJac2 from './images/jackets/leatherJac2.jpg'
export default [
  {
    section: "men",
    category: "outwear",
    subcategory: "jackets",
    id: "1",
    name: "Leather Jacket",
    description: "Classic black leather jacket with zip closure.",
    sizes: [{ size: "S" }, { size: "M" }, { size: "L" }],
    photos: [leatherJac1, leatherJac2 ],
    price: 120,
  },
  {
    section: "men",
    category: "outwear",
    subcategory: "jackets",
    id: "2",
    name: "Denim Jacket",
    description: "Blue denim jacket with button closure.",
    sizes: [{ size: "M" }, { size: "L" }, { size: "XL" }],
    photos: [],
    price: 80,
  },
  {
    section: "men",
    category: "outwear",
    subcategory: "jackets",
    id: "3",
    name: "Bomber Jacket",
    description: "Olive green bomber jacket with ribbed cuffs.",
    sizes: [{ size: "S" }, { size: "M" }],
    photos: [],
    price: 95,
  },
  {
    section: "men",
    category: "outwear",
    subcategory: "jackets",
    id: "4",
    name: "Parka Jacket",
    description: "Water-resistant parka with hood.",
    sizes: [{ size: "M" }, { size: "L" }, { size: "XL" }],
    photos: [],
    price: 150,
  },
  {
    section: "men",
    category: "outwear",
    subcategory: "jackets",
    id: "5",
    name: "Quilted Jacket",
    description: "Warm quilted jacket with front zipper.",
    sizes: [{ size: "S" }, { size: "M" }, { size: "L" }],
    photos: [],
    price: 110,
  },
  {
    section: "men",
    category: "outwear",
    subcategory: "jackets",
    id: "6",
    name: "Suede Jacket",
    description: "Brown suede jacket with snap buttons.",
    sizes: [{ size: "M" }, { size: "L" }],
    photos: [],
    price: 130,
  },
] as Product[];
