import type { Product } from "../../types";

export const jackets: Product[] = [
  {
    section: "men",
    category: "outwear",
    subcategory: "jackets",
    id: "1",
    name: "Leather Jacket",
    description: "Classic black leather jacket with zip closure.",
    sizes: [{ size: "S" }, { size: "M" }, { size: "L" }],
    photos: [],
    price: 120,
  },
  {
    section: "men",
    category: "outwear",
    subcategory: "jackets",
    id: "2",
    name: "Denim Jacket",
    description: "Blue denim jacket with button closure.",
    sizes: [{ size: "M" }, { size: "L" }, { size: "XL" }],
    photos: [],
    price: 80,
  },
  {
    section: "men",
    category: "outwear",
    subcategory: "jackets",
    id: "3",
    name: "Bomber Jacket",
    description: "Olive green bomber jacket with ribbed cuffs.",
    sizes: [{ size: "S" }, { size: "M" }],
    photos: [],
    price: 95,
  },
  {
    section: "men",
    category: "outwear",
    subcategory: "jackets",
    id: "4",
    name: "Parka Jacket",
    description: "Water-resistant parka with hood.",
    sizes: [{ size: "M" }, { size: "L" }, { size: "XL" }],
    photos: [],
    price: 150,
  },
  {
    section: "men",
    category: "outwear",
    subcategory: "jackets",
    id: "5",
    name: "Quilted Jacket",
    description: "Warm quilted jacket with front zipper.",
    sizes: [{ size: "S" }, { size: "M" }, { size: "L" }],
    photos: [],
    price: 110,
  },
  {
    section: "men",
    category: "outwear",
    subcategory: "jackets",
    id: "6",
    name: "Suede Jacket",
    description: "Brown suede jacket with snap buttons.",
    sizes: [{ size: "M" }, { size: "L" }],
    photos: [],
    price: 130,
  },
];

export const hoodies: Product[] = [
  {
    section: "men",
    category: "outwear",
    subcategory: "hoodies",
    id: "4",
    name: "Pullover Hoodie",
    description: "Soft pullover hoodie with front pocket.",
    sizes: [{ size: "S" }, { size: "M" }, { size: "L" }],
    photos: [],
    price: 45,
  },
  {
    section: "men",
    category: "outwear",
    subcategory: "hoodies",
    id: "5",
    name: "Zip-Up Hoodie",
    description: "Black zip-up hoodie with drawstring.",
    sizes: [{ size: "M" }, { size: "L" }],
    photos: [],
    price: 55,
  },
];

export const sweaters: Product[] = [
  {
    section: "men",
    category: "outwear",
    subcategory: "sweaters",
    id: "6",
    name: "Cable Knit Sweater",
    description: "Warm cable knit sweater in grey.",
    sizes: [{ size: "S" }, { size: "M" }, { size: "L" }, { size: "XL" }],
    photos: [],
    price: 60,
  },
  {
    section: "men",
    category: "outwear",
    subcategory: "sweaters",
    id: "7",
    name: "V-Neck Sweater",
    description: "Classic v-neck sweater in navy blue.",
    sizes: [{ size: "M" }, { size: "L" }],
    photos: [],
    price: 50,
  },
];